# Codecov Configuration for Infinimail Backend
# Enforces quality gates for code coverage

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error

  flags:
    unit:
      target: 75%
      threshold: 1%
      paths:
        - internal/
        - pkg/

    integration:
      target: 65%
      threshold: 2%
      paths:
        - tests/integration/

    e2e:
      target: 60%
      threshold: 2%
      paths:
        - tests/e2e/

# Comment configuration
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

# Ignore patterns
ignore:
  - "tests/**"
  - "**/*_test.go"
  - "cmd/**"
  - "*.md"
  - ".github/**"

# GitHub Checks integration
github_checks:
  annotations: true
