package services

import (
	"encoding/json"
	"fmt"
	"strings"
)

// DNSExportFormat represents supported export formats
type DNSExportFormat string

const (
	ExportFormatBIND       DNSExportFormat = "bind"
	ExportFormatCloudflare DNSExportFormat = "cloudflare"
	ExportFormatRoute53    DNSExportFormat = "route53"
	ExportFormatCSV        DNSExportFormat = "csv"
)

// IsValid checks if the export format is valid
func (f DNSExportFormat) IsValid() bool {
	switch f {
	case ExportFormatBIND, ExportFormatCloudflare, ExportFormatRoute53, ExportFormatCSV:
		return true
	}
	return false
}

// DNSExportResult contains the exported DNS records
type DNSExportResult struct {
	Format   DNSExportFormat `json:"format"`
	Content  interface{}     `json:"content"`
	Filename string          `json:"filename"`
}

// CloudflareDNSRecord represents a DNS record in Cloudflare API format
type CloudflareDNSRecord struct {
	Type     string `json:"type"`
	Name     string `json:"name"`
	Content  string `json:"content"`
	Priority int    `json:"priority,omitempty"`
	TTL      int    `json:"ttl"`
	Proxied  bool   `json:"proxied"`
}

// Route53Change represents a change in AWS Route53 format
type Route53Change struct {
	Action            string            `json:"Action"`
	ResourceRecordSet Route53RecordSet  `json:"ResourceRecordSet"`
}

// Route53RecordSet represents a record set in AWS Route53 format
type Route53RecordSet struct {
	Name            string                `json:"Name"`
	Type            string                `json:"Type"`
	TTL             int                   `json:"TTL"`
	ResourceRecords []Route53ResourceRecord `json:"ResourceRecords"`
}

// Route53ResourceRecord represents a resource record value
type Route53ResourceRecord struct {
	Value string `json:"Value"`
}

// Route53ChangeBatch represents a batch of changes for Route53
type Route53ChangeBatch struct {
	Comment string          `json:"Comment"`
	Changes []Route53Change `json:"Changes"`
}

// DNSExporter provides methods to export DNS records in various formats
type DNSExporter interface {
	// ExportBIND exports DNS records in BIND zone file format
	ExportBIND(guide *DNSGuide, domain string) string

	// ExportCloudflare exports DNS records in Cloudflare API JSON format
	ExportCloudflare(guide *DNSGuide, domain string) ([]CloudflareDNSRecord, error)

	// ExportRoute53 exports DNS records in AWS Route53 JSON format
	ExportRoute53(guide *DNSGuide, domain string) (*Route53ChangeBatch, error)

	// ExportCSV exports DNS records as CSV
	ExportCSV(guide *DNSGuide, domain string) string

	// Export exports DNS records in the specified format
	Export(guide *DNSGuide, domain string, format DNSExportFormat) (*DNSExportResult, error)
}

// dnsExporter implements DNSExporter
type dnsExporter struct{}

// NewDNSExporter creates a new DNSExporter instance
func NewDNSExporter() DNSExporter {
	return &dnsExporter{}
}

// ExportBIND exports DNS records in BIND zone file format
func (e *dnsExporter) ExportBIND(guide *DNSGuide, domain string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("; DNS Zone File for %s\n", domain))
	sb.WriteString("; Generated by Infinimail\n")
	sb.WriteString(fmt.Sprintf("$TTL %d\n\n", guide.MXRecord.TTL))

	// MX Record
	sb.WriteString(fmt.Sprintf("; MX Record - Mail server\n"))
	sb.WriteString(fmt.Sprintf("%s.  IN  MX  %d  %s.\n\n",
		guide.MXRecord.Name,
		guide.MXRecord.Priority,
		guide.MXRecord.Value))

	// A Record
	sb.WriteString(fmt.Sprintf("; A Record - Mail subdomain\n"))
	sb.WriteString(fmt.Sprintf("%s.  IN  A  %s\n\n",
		guide.ARecord.Name,
		guide.ARecord.Value))

	// TXT Record
	sb.WriteString(fmt.Sprintf("; TXT Record - Domain verification\n"))
	sb.WriteString(fmt.Sprintf("%s.  IN  TXT  \"%s\"\n",
		guide.TXTRecord.Name,
		guide.TXTRecord.Value))

	return sb.String()
}

// ExportCloudflare exports DNS records in Cloudflare API JSON format
func (e *dnsExporter) ExportCloudflare(guide *DNSGuide, domain string) ([]CloudflareDNSRecord, error) {
	records := []CloudflareDNSRecord{
		{
			Type:     guide.MXRecord.Type,
			Name:     "@", // Cloudflare uses @ for root domain
			Content:  guide.MXRecord.Value,
			Priority: guide.MXRecord.Priority,
			TTL:      guide.MXRecord.TTL,
			Proxied:  false, // MX records cannot be proxied
		},
		{
			Type:    guide.ARecord.Type,
			Name:    "mail", // Subdomain relative to zone
			Content: guide.ARecord.Value,
			TTL:     guide.ARecord.TTL,
			Proxied: false, // Mail servers should not be proxied
		},
		{
			Type:    guide.TXTRecord.Type,
			Name:    "_infinimail", // Subdomain relative to zone
			Content: guide.TXTRecord.Value,
			TTL:     guide.TXTRecord.TTL,
			Proxied: false,
		},
	}

	return records, nil
}

// ExportRoute53 exports DNS records in AWS Route53 JSON format
func (e *dnsExporter) ExportRoute53(guide *DNSGuide, domain string) (*Route53ChangeBatch, error) {
	changeBatch := &Route53ChangeBatch{
		Comment: fmt.Sprintf("Infinimail DNS records for %s", domain),
		Changes: []Route53Change{
			{
				Action: "UPSERT",
				ResourceRecordSet: Route53RecordSet{
					Name: fmt.Sprintf("%s.", guide.MXRecord.Name),
					Type: guide.MXRecord.Type,
					TTL:  guide.MXRecord.TTL,
					ResourceRecords: []Route53ResourceRecord{
						{Value: fmt.Sprintf("%d %s.", guide.MXRecord.Priority, guide.MXRecord.Value)},
					},
				},
			},
			{
				Action: "UPSERT",
				ResourceRecordSet: Route53RecordSet{
					Name: fmt.Sprintf("%s.", guide.ARecord.Name),
					Type: guide.ARecord.Type,
					TTL:  guide.ARecord.TTL,
					ResourceRecords: []Route53ResourceRecord{
						{Value: guide.ARecord.Value},
					},
				},
			},
			{
				Action: "UPSERT",
				ResourceRecordSet: Route53RecordSet{
					Name: fmt.Sprintf("%s.", guide.TXTRecord.Name),
					Type: guide.TXTRecord.Type,
					TTL:  guide.TXTRecord.TTL,
					ResourceRecords: []Route53ResourceRecord{
						{Value: fmt.Sprintf("\"%s\"", guide.TXTRecord.Value)},
					},
				},
			},
		},
	}

	return changeBatch, nil
}

// ExportCSV exports DNS records as CSV
func (e *dnsExporter) ExportCSV(guide *DNSGuide, domain string) string {
	var sb strings.Builder

	// CSV Header
	sb.WriteString("Type,Name,Value,Priority,TTL\n")

	// MX Record
	sb.WriteString(fmt.Sprintf("%s,%s,%s,%d,%d\n",
		guide.MXRecord.Type,
		guide.MXRecord.Name,
		guide.MXRecord.Value,
		guide.MXRecord.Priority,
		guide.MXRecord.TTL))

	// A Record
	sb.WriteString(fmt.Sprintf("%s,%s,%s,,%d\n",
		guide.ARecord.Type,
		guide.ARecord.Name,
		guide.ARecord.Value,
		guide.ARecord.TTL))

	// TXT Record
	sb.WriteString(fmt.Sprintf("%s,%s,\"%s\",,%d\n",
		guide.TXTRecord.Type,
		guide.TXTRecord.Name,
		guide.TXTRecord.Value,
		guide.TXTRecord.TTL))

	return sb.String()
}

// Export exports DNS records in the specified format
func (e *dnsExporter) Export(guide *DNSGuide, domain string, format DNSExportFormat) (*DNSExportResult, error) {
	if !format.IsValid() {
		return nil, fmt.Errorf("invalid export format: %s", format)
	}

	result := &DNSExportResult{
		Format: format,
	}

	switch format {
	case ExportFormatBIND:
		result.Content = e.ExportBIND(guide, domain)
		result.Filename = fmt.Sprintf("%s.zone", domain)

	case ExportFormatCloudflare:
		records, err := e.ExportCloudflare(guide, domain)
		if err != nil {
			return nil, fmt.Errorf("failed to export Cloudflare format: %w", err)
		}
		// Convert to JSON string for content
		jsonBytes, err := json.MarshalIndent(records, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("failed to marshal Cloudflare records: %w", err)
		}
		result.Content = string(jsonBytes)
		result.Filename = fmt.Sprintf("%s-cloudflare.json", domain)

	case ExportFormatRoute53:
		changeBatch, err := e.ExportRoute53(guide, domain)
		if err != nil {
			return nil, fmt.Errorf("failed to export Route53 format: %w", err)
		}
		// Convert to JSON string for content
		jsonBytes, err := json.MarshalIndent(changeBatch, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("failed to marshal Route53 records: %w", err)
		}
		result.Content = string(jsonBytes)
		result.Filename = fmt.Sprintf("%s-route53.json", domain)

	case ExportFormatCSV:
		result.Content = e.ExportCSV(guide, domain)
		result.Filename = fmt.Sprintf("%s-dns.csv", domain)
	}

	return result, nil
}
